In [ ]:
import numpy as np


In [ ]:
arr= np.array([1,2,3,4,5])
reversed = arr[::-1]
reversed

array([5, 4, 3, 2, 1])

In [ ]:
arr=np.array([[1,2,3],[2,4,5],[1,2,3]])
flatten=arr.flatten()
flatten

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

comparison = np.array_equal(arr1, arr2)
comparison

True

In [ ]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def most_frequent(arr):
    unique, counts = np.unique(arr, return_counts=True)
    most_frequent_value = unique[np.argmax(counts)]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices

mf_x, idx_x = most_frequent(x)
mf_y, idx_y = most_frequent(y)




Array x: Most frequent value = 1, Indices = [0 5 7 8 9]
Array y: Most frequent value = 1, Indices = [0 1 2]


In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total_sum = np.sum(gfg)
print(f"Sum of all elements: {total_sum}")
row_sum = np.sum(gfg, axis=1)
print(f"Sum of all elements row-wise: {row_sum}")
col_sum = np.sum(gfg, axis=0)
print(f"Sum of all elements column-wise: {col_sum}")


Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


In [ ]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

sum_diagonal = np.trace(n_array)
print(f"Sum of diagonal elements: {sum_diagonal}")

eigenvalues, eigenvectors = np.linalg.eig(n_array)
print(f"Eigenvalues of the matrix: {eigenvalues}")
print(f"Eigenvectors of the matrix:\n{eigenvectors}")

inverse_matrix = np.linalg.inv(n_array)
print(f"Inverse of the matrix:\n{inverse_matrix}")

determinant = np.linalg.det(n_array)
print(f"Determinant of the matrix: {determinant}")


Sum of diagonal elements: 176
Eigenvalues of the matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of the matrix:
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


In [ ]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

product1 = np.dot(p1, q1)

flatten_p1 = p1.flatten()
flatten_q1 = q1.flatten()
cov_matrix1 = np.cov(flatten_p1, flatten_q1, ddof=0)

print("Matrix multiplication result (i):")
print(product1)
print("Covariance matrix (i):")
print(cov_matrix1)

# Define the matrices for part (ii)
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

# Matrix multiplication
product2 = np.dot(p2, q2)

# Covariance between matrices
# Flattening matrices and stacking them for covariance calculation
flatten_p2 = p2.flatten()
flatten_q2 = q2.flatten()
cov_matrix2 = np.cov(flatten_p2, flatten_q2, ddof=0)  # ddof=0 for population covariance

print("Matrix multiplication result (ii):")
print(product2)
print("Covariance matrix (ii):")
print(cov_matrix2)

Matrix multiplication result (i):
[[16 19]
 [26 31]]
Covariance matrix (i):
[[0.5  0.75]
 [0.75 1.25]]
Matrix multiplication result (ii):
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix (ii):
[[1.80555556 0.19444444]
 [0.19444444 4.47222222]]


In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.dot(x, y.T)
outer_products = [np.outer(x_row, y_row) for x_row in x for y_row in y]
cartesian_products = np.array([[np.outer(x_i, y_j) for y_j in y] for x_i in x])
print("Inner Product:\n", inner_product)
for i, outer_product in enumerate(outer_products):
    print(f"Outer Product of row {i//2+1} of x with row {i%2+1} of y:\n", outer_product)
print("Cartesian Product:\n", cartesian_products)

Inner Product:
 [[17 52]
 [13 62]]
Outer Product of row 1 of x with row 1 of y:
 [[ 2 10  0]
 [ 3 15  0]
 [ 4 20  0]]
Outer Product of row 1 of x with row 2 of y:
 [[10 20  6]
 [15 30  9]
 [20 40 12]]
Outer Product of row 2 of x with row 1 of y:
 [[ 3 15  0]
 [ 2 10  0]
 [ 9 45  0]]
Outer Product of row 2 of x with row 2 of y:
 [[15 30  9]
 [10 20  6]
 [45 90 27]]
Cartesian Product:
 [[[[ 2 10  0]
   [ 3 15  0]
   [ 4 20  0]]

  [[10 20  6]
   [15 30  9]
   [20 40 12]]]


 [[[ 3 15  0]
   [ 2 10  0]
   [ 9 45  0]]

  [[15 30  9]
   [10 20  6]
   [45 90 27]]]]


In [ ]:
# QUESTION 2 :-

In [ ]:
#2(a) i
array = np.array([[1, -2, 3], [-4, 5, -6]])

abs_array = np.abs(array)
print(abs_array)

#ii
percentiles_flattened = np.percentile(array, [25, 50, 75])
print("Percentiles of flattened array:", percentiles_flattened)

percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
print("Percentiles for each column:\n", percentiles_columns)

percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles for each row:\n", percentiles_rows)

#iii
mean_flattened = np.mean(array)
median_flattened = np.median(array)
std_flattened = np.std(array)
print("Flattened array - Mean:", mean_flattened, "Median:", median_flattened, "Std Dev:", std_flattened)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)
print("Columns - Mean:", mean_columns, "Median:", median_columns, "Std Dev:", std_columns)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)
print("Rows - Mean:", mean_rows, "Median:", median_rows, "Std Dev:", std_rows)


[[1 2 3]
 [4 5 6]]
Percentiles of flattened array: [-3.5 -0.5  2.5]
Percentiles for each column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Flattened array - Mean: -0.5 Median: -0.5 Std Dev: 3.8622100754188224
Columns - Mean: [-1.5  1.5 -1.5] Median: [-1.5  1.5 -1.5] Std Dev: [2.5 3.5 4.5]
Rows - Mean: [ 0.66666667 -1.66666667] Median: [ 1. -4.] Std Dev: [2.05480467 4.78423336]


In [ ]:
#2(b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

# Floor values
floor_values = np.floor(a)
print("Floor values:", floor_values)

# Ceiling values
ceiling_values = np.ceil(a)
print("Ceiling values:", ceiling_values)

# Truncated values
truncated_values = np.trunc(a)
print("Truncated values:", truncated_values)

# Rounded values
rounded_values = np.round(a)
print("Rounded values:", rounded_values)






Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
#QUESTION 3 (A)

In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)

# ii. Indices of sorted array
indices_sorted_array = np.argsort(array)

# iii. 4 smallest elements
four_smallest_elements = np.sort(array)[:4]

# iv. 5 largest elements
five_largest_elements = np.sort(array)[-5:]

print("Sorted array:", sorted_array)
print("Indices of sorted array:", indices_sorted_array)
print("4 smallest elements:", four_smallest_elements)
print("5 largest elements:", five_largest_elements)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [ ]:
arr = np.array([1, 2.5, 3, 4.0, 5, 6.7])

int_elements = arr[arr == arr.astype(int)]
print("Integer elements:", int_elements)

float_elements = arr[arr != arr.astype(int)]
print("Float elements:", float_elements)

Integer elements: [1. 3. 4. 5.]
Float elements: [2.5 6.7]


In [ ]:
!pip install google-colab
from PIL import Image
from google.colab import files

def img_to_array(filename='content/OIP.jpg'):
    img = Image.open(filename)

    img_array = np.array(img)

    # Determine the file extension based on the image mode (RGB or L)
    if img.mode == 'RGB':
        file_name = 'rgb_image.txt'
    elif img.mode == 'L':  # Grayscale
        file_name = 'grey_image.txt'
    else:
        raise ValueError("Unsupported image mode")

    # Save the numpy array to a text file
    np.savetxt(file_name, img_array, fmt='%d')

    print(f"Image data saved to {file_name}") # Changed 'content' to 'file_name' to display the correct saved file.

uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# Convert and save the image
img_to_array(image_path)

  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def load_and_display_image(file_name):
    img_array = np.loadtxt(file_name, dtype=np.uint8)
    plt.imshow(img_array, cmap='gray' if len(img_array.shape) == 2 else 'rgb')
    plt.axis('off')
    plt.show()

load_and_display_image('rgb_image.txt')